services:
  db:
    image: postgres:16-alpine
    container_name: chats_apps_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_DB: ${POSTGRES_DB-postgres}
    ports:
      - ${POSTGRES_PORT-5431}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER-postgres} -d ${POSTGRES_DB-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - chat-app-networks
networks:
  chat-app-networks:
    driver: bridge
volumes:
  postgres_data: